export const productMeta = {
  name: 'DraftFlow',
  tagline: 'Draft social replies without leaving the thread. You stay in control.',
  iconSrc: '/icon-128.png',
  trust: {
    privacy: 'Local-first · Your keys stay yours',
    badges: ['Free tier', 'Privacy first', 'MV3 ready'],
    rating: '4.9',
  },
  slides: [
    {
      id: '01',
      type: 'hero',
      image: '/assets/raw/1.png',
      kicker: 'Engage faster',
      headline: 'AI reply angles in one click',
      subline: 'Highlight text or open a reply box — DraftFlow suggests on-brand angles instantly.',
    },
    {
      id: '02',
      type: 'workflow',
      image: '/assets/raw/2.png',
      kicker: 'Precision replies',
      headline: 'Reply only to what you highlight',
      subline: 'Skip the noise. DraftFlow reads your selection, not the whole thread.',
      pills: ['Selected text only', 'Side panel flow', 'Keyboard shortcut'],
    },
    {
      id: '03',
      type: 'feature',
      image: '/assets/raw/3.png',
      kicker: 'Choose your angle',
      headline: 'Pick the reply that fits',
      subline: 'Multiple AI-generated angles — you edit, you send.',
      pills: ['Tone-aware', 'On-brand voice', 'One-tap fill'],
    },
    {
      id: '04',
      type: 'workflow',
      image: '/assets/raw/4.png',
      kicker: 'Create mode',
      headline: 'Save inspirations, draft similar posts',
      subline: 'Bookmark posts you admire. DraftFlow helps you create in the same voice.',
      pills: ['Save inspirations', 'Similar drafts', 'Side panel'],
    },
    {
      id: '05',
      type: 'workflow',
      image: '/assets/raw/7.png',
      kicker: 'Create workflow',
      headline: 'Filter saved posts, draft from the panel',
      subline: 'Browse your library and spin up on-brand posts without context switching.',
      pills: ['Filter by tag', 'Batch browse', 'One-click draft'],
    },
    {
      id: '06',
      type: 'feature',
      image: '/assets/raw/8.png',
      kicker: 'Post assistant',
      headline: 'Draft posts with AI in Create mode',
      subline: 'Pick a saved inspiration and shape your next post from the side panel.',
      pills: ['Create mode', 'On-brand output', 'You always publish'],
    },
    {
      id: '07',
      type: 'checklist',
      images: [
        { src: '/assets/raw/9.png', label: 'Post checklist' },
        { src: '/assets/raw/10.png', label: 'Reply checklist' },
      ],
      kicker: 'AI Optimization Checklist',
      headline: 'Optimize before you publish',
      subline: 'Post and reply checklists score drafts against your playbook rules.',
      pills: ['Post + Reply modes', 'Actionable fixes', 'One-tap Optimize'],
    },
    {
      id: '08',
      type: 'trust',
      images: [
        { src: '/assets/raw/5.png', label: 'On-brand voice' },
        { src: '/assets/raw/6.png', label: 'Usage tracking' },
      ],
      kicker: 'Your voice, your keys',
      headline: 'Settings you control',
      subline: 'Train from your posts. Bring your own API key. You always send.',
      cta: 'Add to Chrome',
    },
  ],
};

export const promoMeta = {
  screenshotHero: '/assets/raw/1.png',
  screenshotCreate: '/assets/raw/8.png',
};
