export const productMeta = {
  name: 'CWS Asset Generator',
  tagline: 'Agent skill — raw screenshots to store-ready listing graphics.',
  iconSrc: '/icon-128.png',
  trust: {
    privacy: 'Local preview · No cloud upload required',
    badges: ['4 style packages', '1280×800 exact', 'Copy gate', 'Batch export'],
    rating: '5.0',
  },
  slides: [
    {
      id: '01',
      type: 'hero',
      image: '/assets/raw/1.png',
      kicker: 'Agent skill workflow',
      headline: 'Raw screenshots to store graphics',
      subline:
        'Drop extension captures in a folder — get 4 styled screenshot sets and promo tiles at exact CWS dimensions.',
      pills: [],
    },
    {
      id: '02',
      type: 'workflow',
      image: '/assets/raw/2.png',
      kicker: 'Phase 2 — Asset intake',
      headline: 'Map filenames to slide roles',
      subline: 'Scan your folder, confirm naming convention, build assetMap before any design work.',
      pills: ['Numbered or descriptive names', 'Dual-image slides', 'Single source of truth'],
    },
    {
      id: '03',
      type: 'feature',
      image: '/assets/raw/3.png',
      kicker: 'Phase 3 — Copy proposal',
      headline: 'Three variants per slide',
      subline: 'Benefit-led, feature-led, and outcome-led copy — you pick or edit before design starts.',
      pills: ['Variant A / B / C tables', 'Promo tile copy', 'No lorem placeholders'],
    },
    {
      id: '04',
      type: 'workflow',
      image: '/assets/raw/4.png',
      kicker: 'Phase 4 — Copy gate',
      headline: 'Sign off every slide first',
      subline: 'Design and export stay blocked until copy is approved slide-by-slide.',
      pills: ['Per-slide confirmation', 'copy.lock.json optional', 'Revision by slide ID'],
    },
    {
      id: '05',
      type: 'feature',
      image: '/assets/raw/5.png',
      kicker: 'Phase 5 — Visual styles',
      headline: 'Four complete style packages',
      subline: 'Same approved copy and assets — Clean Minimal, Neon Tech, Warm Editorial, Bold Contrast.',
      pills: ['1280×800 screenshots', 'Shared assetMap', 'Independent theme tokens'],
    },
    {
      id: '06',
      type: 'feature',
      image: '/assets/raw/6.png',
      kicker: 'Phase 6 — Local preview',
      headline: 'Tabbed browser preview',
      subline: 'Run npm run dev — switch styles, inspect cards, export individual PNGs with one click.',
      pills: ['StoreAssetsPreview.jsx', 'html2canvas export', 'Puppeteer batch script'],
    },
    {
      id: '07',
      type: 'checklist',
      images: [
        { src: '/assets/raw/7.png', label: 'Promo — logo focus' },
        { src: '/assets/raw/8.png', label: 'Promo — UI banner' },
      ],
      kicker: '440×280 promo tiles',
      headline: 'Three small promo layouts',
      subline: 'Logo focus, UI banner, and trust-badge strip — all at mandatory CWS promo size.',
      pills: ['440×280 exact', '3 layout options', 'Same copy lock'],
    },
    {
      id: '08',
      type: 'trust',
      images: [
        { src: '/assets/raw/9.png', label: 'Batch export' },
        { src: '/assets/raw/10.png', label: 'Revision loop' },
      ],
      kicker: 'Phase 7 — Ship',
      headline: 'Export and iterate by ID',
      subline: 'Batch PNGs to export/ — tweak copy or swap assets via style-b-slide-04 and re-export.',
      cta: 'Install skill',
    },
  ],
};

export const promoMeta = {
  screenshotHero: '/assets/raw/6.png',
  promoHeadline: 'Approve copy. Export PNGs.',
  promoSubline: '4 styles · exact CWS sizes',
};
