export const themeA = {
  id: 'a',
  label: 'Clean Minimal',
  canvas: 'bg-[#0A0D14]',
  text: 'text-white',
  subtext: 'text-white/60',
  kicker: 'text-white/45 uppercase tracking-[0.2em] text-xs font-medium',
  heading: 'font-sans font-semibold tracking-tight text-white text-5xl leading-tight',
  subline: 'text-white/55 text-xl max-w-2xl',
  flare: 'absolute w-[520px] h-[520px] rounded-full bg-white/[0.07] blur-3xl',
  window: 'rounded-xl border border-white/10 bg-[#1C1C1E] shadow-[0_24px_80px_rgba(0,0,0,0.45)] overflow-hidden',
  windowBar: 'h-9 bg-[#2C2C2E] border-b border-white/10 flex items-center px-3 gap-1.5',
  dot: 'w-2.5 h-2.5 rounded-full',
  pill: 'bg-white/10 text-white/80 border border-white/15 rounded-full px-3 py-1 text-sm',
  badge: 'bg-white/10 border border-white/15 text-white/90 rounded-full px-4 py-1.5 text-sm',
  cta: 'bg-white text-black font-semibold px-8 py-3 rounded-full text-lg',
  accent: 'text-white',
  grid: '',
  imageWrap: 'bg-[#0B0B0D] p-1',
};

export const themeB = {
  id: 'b',
  label: 'Neon Tech',
  canvas: 'bg-[#030712] bg-grid-cyber bg-grid',
  text: 'text-white',
  subtext: 'text-slate-400',
  kicker: 'text-cyan-400/80 uppercase tracking-[0.22em] text-xs font-bold',
  heading: 'font-sans font-bold tracking-tight text-white text-5xl leading-tight',
  subline: 'text-slate-400 text-xl max-w-2xl',
  flare: 'absolute w-[480px] h-[480px] rounded-full bg-indigo-500/20 blur-3xl',
  window:
    'rounded-lg border border-indigo-500/30 bg-[#0B0F19] shadow-[0_0_40px_rgba(56,189,248,0.15)] overflow-hidden',
  windowBar: 'h-9 bg-[#111827] border-b border-indigo-500/20 flex items-center px-3 gap-1.5',
  dot: 'w-2.5 h-2.5 rounded-full',
  pill: 'bg-indigo-500/20 text-cyan-300 border border-indigo-500/40 rounded-md px-2.5 py-0.5 text-xs font-medium uppercase tracking-wider',
  badge: 'bg-indigo-500/15 border border-cyan-500/30 text-cyan-200 rounded-md px-3 py-1 text-xs uppercase tracking-wide',
  cta: 'bg-cyan-400 text-[#030712] font-bold px-8 py-3 rounded-md text-lg shadow-[0_0_24px_rgba(34,211,238,0.35)]',
  accent: 'text-cyan-400',
  grid: 'opacity-100',
  imageWrap: 'bg-[#060a14] p-1',
};

export const themeC = {
  id: 'c',
  label: 'Warm Editorial',
  canvas: 'bg-[#FAF8F5]',
  text: 'text-stone-900',
  subtext: 'text-stone-500',
  kicker: 'text-stone-400 uppercase tracking-[0.18em] text-xs font-medium',
  heading: 'font-editorial font-medium tracking-tight text-stone-900 text-5xl leading-tight',
  subline: 'text-stone-500 text-xl max-w-2xl',
  flare: 'absolute w-[500px] h-[500px] rounded-full bg-amber-100/60 blur-3xl',
  window:
    'rounded-xl border border-stone-200/80 bg-white shadow-2xl shadow-stone-900/5 overflow-hidden',
  windowBar: 'h-9 bg-stone-50 border-b border-stone-200 flex items-center px-3 gap-1.5',
  dot: 'w-2.5 h-2.5 rounded-full',
  pill: 'bg-stone-100 text-stone-600 border border-stone-200 rounded-full px-3 py-1 text-sm',
  badge: 'bg-stone-100 border border-stone-200 text-stone-700 rounded-full px-4 py-1.5 text-sm',
  cta: 'bg-stone-900 text-white font-medium px-8 py-3 rounded-lg text-lg shadow-lg shadow-stone-900/10',
  accent: 'text-amber-800/90',
  grid: '',
  imageWrap: 'bg-stone-50 p-1',
};

export const themeD = {
  id: 'd',
  label: 'Bold Contrast',
  canvas: 'bg-[#0F0F0F]',
  text: 'text-white',
  subtext: 'text-neutral-400',
  kicker: 'text-[#FF4D00] uppercase tracking-[0.25em] text-xs font-black',
  heading: 'font-sans font-black tracking-tighter text-white text-5xl leading-none uppercase',
  subline: 'text-neutral-400 text-xl max-w-2xl',
  flare: 'absolute w-[400px] h-[400px] rounded-full bg-[#FF4D00]/10 blur-3xl',
  window: 'rounded-none border-2 border-white/20 bg-[#1A1A1A] shadow-none overflow-hidden',
  windowBar: 'h-9 bg-black border-b-2 border-white/20 flex items-center px-3 gap-1.5',
  dot: 'w-2.5 h-2.5 rounded-full',
  pill: 'bg-[#FF4D00] text-white rounded-sm px-3 py-1 text-xs font-bold uppercase',
  badge: 'border-2 border-white/30 text-white rounded-sm px-3 py-1 text-xs font-bold uppercase',
  cta: 'bg-[#FF4D00] text-white font-black px-8 py-3 rounded-sm text-lg uppercase tracking-wide',
  accent: 'text-[#FF4D00]',
  grid: '',
  imageWrap: 'bg-black p-1',
};

export const themes = [themeA, themeB, themeC, themeD];
